[tool.poetry]
name = "Kyoyobot"
version = "0.1.0"
description = "ğŸ›"
authors = ["96 LB <96lb@96lb.ml>", "A bunch of other people probably"]

[tool.poetry.dependencies]
python = ">=3.11.0"
flask = "^2.1.2"
discord = "^2.2.2"

[tool.poetry.dev-dependencies]

[tool.pyright]
strict = ["**"]
venv = ".venv"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
